### ISSUE TITLE
comentarios avance 2

### ISSUE THREAD

**Issue by AliciaMstt** [Bendxg/Proyecto-Final-Bioinf2017-II#2]
Tal como te comenté en tu avance 1, para tu avance 2 tenías que **ya** tener los datos descargados. De tu avance 2 entiendo que le escribiste a los autores, pero no que ya los tengas. 

Tu proyecto no presenta los avances esperados y me preocupa que no puedas entregarlo satisfactoriamente en la entrega final. De ser así, y como te pedí desde el avance 1 que tuvieras cuidado, no podré tener consideraciones.

**Comment by Bendxg** [comment]
Hola. Ok. Apenas ví los comentarios del avance 1 cuando recibí los del avance 2. Ya tengo las secuencias, se tardaron en enviárlas pero ya las tengo. Gracias.

**Comment by AliciaMstt** [comment]
Ok. Muy bien.
