### ISSUE TITLE
comentarios avance 3 y readme

### ISSUE THREAD

**Issue by AliciaMstt** [Bendxg/Proyecto-Final-Bioinf2017-II#3]
Sobre tu avance:

1) Te faltó poner un espacio después del # para que se vea bien el título del avance. Corrígelo por favor.

2) Sobre tu duda de cómo entregar el trabajo, te pido que revises [esta sección del repositorio de la clase](https://github.com/AliciaMstt/BioinfinvRepro/blob/master/TrabajoFinal/Instrucciones_Proyecto_final.md#contenido-del-proyecto-final) donde explico justamente qué hacer en caso de que los archivos de tu trabajo sean grandes.

Sobre tu README:

Pon también el nombre de los scripts, no namás el nombre de los directorios donde están.

**Comment by Bendxg** [comment]
Listo. 
Gracias!
